### ISSUE TITLE
Bar - eccentricity null when zero

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#101]
Bar component returns null instead of zero when deconstructed. This causes error if construct bar uses the eccentricty property of deconstruct bar

**Comment by andosca** [comment]
@andosca See related files in 101 - Eccentricity error

**Comment by Marco-Pellegrino** [comment]
![image](https://user-images.githubusercontent.com/53620289/180784181-8b2afaad-fdcd-4503-a8ae-40eaae8c1a95.png)


The deconstructor return the eccentricity value and not null.

`UseDefaultPhysicalAlignment` has been set to false in order to match the value in the analytical model as suggested in FogBugz.
