### ISSUE TITLE
GetBars() takes too long to run in large models when deserializing struxml

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#168]
The script takes around 10 min to run for a customer project struxml file, which is a bit longer than we would like.
@xRadne thinks that we can decrease this time to seconds if we do some code optimization

Could also be the same with GetPanels(), GetSlabs() etc.

@andosca could we prioritize this?

**Comment by xRadne** [comment]
For example this part could be exchanged to a lookup-table (`Dictionary` or something)

https://github.com/strusoft/femdesign-api/blob/7310c9a79622a9676cc3d174290d2433c1543ff3/FemDesign.Core/Model/Model.cs#L2557-L2563

**Comment by andosca** [comment]
Good idea to use dictionaries in https://github.com/strusoft/femdesign-api/commit/b1e0bdb94737fc76ffa4cea83c01073cdb4ca47e! 👍

**Comment by xRadne** [comment]
A bit more could be done but it's a start at least. 

A big part of the problem was the `.DeepClone()` method being fun in each iteration in inner loop, instead of once per object. 

The PTC and BarReinfocement have not been refactored in `.GetBars()`

Also the other methods (`model.GetSlabs()` etc) could also be improved.

**Comment by xRadne** [comment]
Current solution is sufficient but further improvements can be made if needed
