### ISSUE TITLE
Load Case/Comb. Types, Duration etc. needs better parsing

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#186]
Should be parseable directly from the values from 
- [x] FEM-Design GUI
- [x] `.struxml`-file
- [x] `.ldcase`-file
- [x] `.ldcomb`-file

![MicrosoftTeams-image](https://user-images.githubusercontent.com/32938476/152115006-8dfce9f1-4a16-423c-9627-573059ea0ae8.png)

**Comment by xRadne** [comment]
@samnyb For your interest

**Comment by andosca** [comment]
Do you need help translating the representations in GUI vs .struxml?

**Comment by xRadne** [comment]
Should be fine. But what does the `+` stand for?

**Comment by andosca** [comment]
`+`means that it will consider the loads defined in the specific load case `+` the specific effect.

For example:

`+Struc. dead load` = Any loads in the load case `+` the dead load of the elements in the model.
`+Shrinkage` = Any loads in the load case `+` any forces caused by restrained shrinkage.
