### ISSUE TITLE
Slab component cannot read flat surface outlines

### ISSUE THREAD

**Issue by samnyb** [strusoft/femdesign-api#279]
The `Slab.Wall` component sometimes cannot properly read surfaces. In this case, four flat, simple surfaces gave the error.

Error message:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/97892858/158832764-ef388fa1-3bfc-4da5-96d0-a4e69762fe40.png)
 
Component setup:
![temp](https://user-images.githubusercontent.com/97892858/158832827-dc37014f-8a09-4280-8795-c59e122f4a0b.png)

As you can see, the issue can be fixed by taking the surfaces apart and reconstructing them, for whatever reason. The surfaces are planar and have reasonable orientations.

Files recreating this issue, both .3dm surfaces and .gh script, are available in the Test files folder.

**Comment by andosca** [comment]
This error occurs due to a bad method implemented long ago (git blame andosca). 

We should update this method as it might not always work for some specific shapes.

https://github.com/strusoft/femdesign-api/blob/8387cdb1ee438620727d142bafa231c2d7efd706/FemDesign.Grasshopper/Geometry/Convert.cs#L514-L670

This would be a good opportunity to have a look at obfuscating the `Edge` class as well.

**Comment by andosca** [comment]
Might be related to: #455

**Comment by Marco-Pellegrino** [comment]
I have insvestigate the issue and tested the code with several input surfaces.
It looks like that the provided example has some Slab Elements longer than 2000 meter! Bring those back to 200 meter (still a really big slab) would make the code working as expected.

It is really unlikely that a user will want to design a 2 km slab (if that happen,  😮) and I believe we can close the case.
