### ISSUE TITLE
Example 4: C# Deconstruct a model, edit and reconstruct

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#293]
### Extract info from model
- [x] Show deconstruct in several steps: model -> bar -> Material/section. `Console.WriteLine`

### Create/Update model
- [x] Use component `Model.AddElements`. Explain `overwrite` boolean
- [x] Use component `new FemDesign.Model` and compare to `model.AddElements`. Isolate one floor slab and the associated loads. Put point supports at point where the columns were and line supports where the walls were. 

### Open model
- [x] Open model at the end

**Comment by samnyb** [comment]
**Problem 1:**
I open the project in Visual Studio, and it seems to me that I have all the files I need, but something isn't working. I can't build the solution - it says I have the wrong framework referenced, but I can't find where it is wrong - and I can't run ´Main.cs´, because it says it has to be debugged first.

**Comment by samnyb** [comment]
**Problem 1:**
I open the project in Visual Studio, and it seems to me that I have all the files I need, but something isn't working. I can't build the solution - it says I have the wrong framework referenced, but I can't find where it is wrong - and I can't run ´Main.cs´, because it says it has to be debugged first.
