### ISSUE TITLE
C# Example: Mesh size convergence check

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#321]
### Part 1
INPUT:
- **File path** to Model (.str/.struxml) with labelled sections [-]
- List of **mesh sizes** to try [mm]
- Max **allowed deviation** [%]

OUTPUT:
- Table

Meshstorlek [mm] | \<Some force> Txz | Avvikelse [%]
--- | --- | ---
1.0 | 4.0 | -
0.5 | 8.0 | 100%
0.25 | 10.0 | 25%
0.20 | 11.0 | 10%
0.15 | 11.1 | 1%
0.10 | 11.2 | 1%

- [x] Script for part 1

### Part 2
Like part 1 but also creating the result points / labelled sections for the user automatically

- [ ] Script for part 2

**Comment by xRadne** [comment]
Maybe also
- Export to excel
- Create a plot like below
 
![image](https://user-images.githubusercontent.com/32938476/165092836-156c0458-7964-4544-b4d7-e0710139b3ba.png)

**Comment by samnyb** [comment]
Current output looks something like

Meshstorlek [mm] | Nx' total [Nmm/mm] | Avvikelse total [Nmm/mm] | Avvikelse [%]
--- | --- | --- | ---
1.0 | 4.0 | - | -
0.5 | 20.0 | 20.0 | 100%
0.25 | 19.3 | 4.8 | 25%
0.20 | 11.0 | 1.2 | 10%
0.15 | 11.1 | 1.0 | 1%
0.10 | 11.2 | 1.0 | 1%

**Comment by samnyb** [comment]
We consider this example done! In the future, when the results reader is properly implemented, we might want to change the example from the current method of reading data (index to read from an .csv file) to the new method. 

Comments above, like the Part 2 task, writing to excel, and making a graph, have also yet to be implemented. I suggest whoever does the results reader changes does this as well.

For now, however, this issue is closed, and can be reopened once relevant again.
