### ISSUE TITLE
Upload the Dynamo examples (wiki) to Github

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#342]
- [X] Hello world
- [x] Hyperbolic shell

**Comment by samnyb** [comment]
- [X] Hello world
- [ ] Hyperbolic shell

**Comment by samnyb** [comment]
@xRadne I decided against using the Hyperbolic shell example after all, because Lunchbox for Dynamo is [discontinued](https://apps.provingground.io/lunchbox/) since [2020](https://bitbucket.org/provingground-io/lunchbox-for-dynamo/src/master/). Before this, you could just install it from the Dynamo package manager, however now you have to download the repo and install it that way.

I feel like that's too much for for a discontinued plugin, for an example we won't use that much, but if you feel like this was the wrong call, feel free to veto!

**Comment by xRadne** [comment]
Ok!
