### ISSUE TITLE
Rigidity_group

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#463]
Implement `rigidity_group` for edge connections and line supports and point supports:

https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Core/Supports/Group.cs

Will need to update the deconstructor as well:

https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Grasshopper/Deconstruct/SupportDeconstruct.cs

And probably

https://github.com/strusoft/femdesign-api/blob/master/FemDesign.Grasshopper/Deconstruct/EdgeConnectionDeconstruct.cs

**Comment by AmalieRask131** [comment]
I am experiencing some problems with rigidity_groups also for Point Support Groups - It seems that the deconstructor is not able to read it as well - do you look into that also?

**Comment by andosca** [comment]
@AmalieRask131 
Yes. We will implement it for point supports as well. Thanks for pointing it out. 

Are you using different stiffness for different calculations?

![](https://user-images.githubusercontent.com/52665994/185639092-75dd148e-386f-4372-8644-c06360833e43.png)

**Comment by AmalieRask131** [comment]
@andosca Currently we are using the api to populate a model with loads, containing the building foundation beams and piles. Support groups are used instead of piles, and often we want to restrict the the compression limit of the piles according to the measured values from the building site, to obtain a plastic redistribution.
(i'm not quite sure, but) it looks like the spring-stiffness for some situations is reduced in ULS only, being fully rigid in SLS - NOT using the 'same for all calculations'.

**Comment by andosca** [comment]
@AmalieRask131
Ok so then this issue might be a blocker for you. We will implement it ASAP :)

**Comment by Marco-Pellegrino** [comment]
Hi @AmalieRask131!
if you like, you can build 21.4.0 and try the rigidity group.
It will give you access to the Rigidity Group and you can serialise/deserialise the model as usual :)
I hope it helps

**Comment by andosca** [comment]
Works fine.
