### ISSUE TITLE
Predefine Section or Material does not get read in FEM-Design

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#491]
FEM-Design will not be able to add the Bar to the model

![image](https://user-images.githubusercontent.com/53620289/188823656-2b718469-79a9-4cf6-8ee4-92cbd41971c9.png)
![Capture](https://user-images.githubusercontent.com/53620289/188823903-608167b2-da00-4e9d-978d-1c5d6926e7cf.jpg)

**Comment by xRadne** [comment]
I implemented a cache for `MaterialDatabase.GetDefault()` this might have caused the issue. But I don't think so. The only difference should be that the code `MaterialDatabase.GetDefault()` only runs once instead of everytime.

However, this might be related a bug we had earlier that the material guids don't match if we read the materialdatabase several times. #283

https://github.com/strusoft/femdesign-api/commit/d8040641d880c4c0f0eac7fcb33503a83e760f61

**Comment by Marco-Pellegrino** [comment]
The bug has been removed removing the automatic section features that it was creating a difficult bug to spot.

A Material Guid modified his self in a certain part of the code after his initialitation (which is correct)

**Comment by xRadne** [comment]
What line was modifying the guid of the sections? :)
