### ISSUE TITLE
Error message when type of analysis does not exist/is not set up

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#590]
I have come across several users who have the problem that they try to run an analysis which is not set up or does not exist (for example model contains no load combinations). It locks the GH script and you have to close down the FD instance. Could we create an error handler for this common user mistake?
![image](https://user-images.githubusercontent.com/89396751/200311601-cb128afa-c612-4157-990f-74703691aeb2.png)

**Comment by xRadne** [comment]
@Marco-Pellegrino What do you mean? I can run analysis with `calcGmax`, `calcStab` and `calcSeis` :)

I have raised a bug for `CalcImp` on FogBugz https://strusoft.fogbugz.com/f/cases/122810/StruXml-Can-t-run-imperfection-analysis. This is a bug in fdscript, but will be fixed in FEM-Design `21.00.006`

**Comment by Marco-Pellegrino** [comment]
Interesting.

How do we run CalcSeis if we can not specify anything about the seismic analysis?

How do we run CalcStab if we can not specify any settings?

**Comment by xRadne** [comment]
Stability analysis settings are on the `CombItem`

If you have a model (`.str`) with elements, loads and setting you can run the seisemic analysis in C# at least. But I realise now that we can't run the seisemic analysis in grasshopper since the component require a Model (struxml) as well. However with the pipe I think we can make this work :)
