### ISSUE TITLE
Construct and AddElements does not share input parameters

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#698]
![image](https://user-images.githubusercontent.com/52665994/217752993-3689be8d-fa28-4529-b2d0-8dd7a903b314.png)

Soil and Stages are missing from AddElements - by design? @Marco-Pellegrino

**Comment by Marco-Pellegrino** [comment]
@andosca 
Not really by design.
I haven't just considered the implementation. 😅

In general, the user can still Deconstruct and Construct a new model with new elements if he needs to add elements?

But I definitely like the idea to add Soil and Stages (less inportant).
Feel free to add it for next milestone

**Comment by andosca** [comment]
> In general, the user can still Deconstruct and Construct a new model with new elements if he needs to add elements?
Not really as not everything can be deconstructed right now.

Ok.

**Comment by Marco-Pellegrino** [comment]
- [ ] Soil
- [ ] Stages

**Comment by Marco-Pellegrino** [comment]
Add soil is implemented.

Stages will not be implemented as it has not been requested by a user. The task is more difficult than previously assumed
