### ISSUE TITLE
Those ConstructionStages attributes should not be on the .struxml ?

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#737]
Those attributes should not be on the .struxml
- [ ] ghost
- [ ] time-dependent_analysis
- [ ] creep_strain_increment_limit

_Originally posted by @Marco-Pellegrino in https://github.com/strusoft/femdesign-api/issues/716#issuecomment-1466227118_

**Comment by lorinczandrea** [comment]
Answer from the FD developers:

**ghost:** 

- This attribute is built into the FD model objects, which is why it appears in the .struxml file. Basically .struxml follows the FD model objects, so anything that is in them will appear in the .struxml schema. (This is the system that Laci follows)
- In FD, this "ghost" attribute is shown as a calculation option, this is what the user sees. In the .fdscript file we can control the settings that appear in the calculation window, so Pasa implemented the "ghost" option in the .fdscript file. (This is the system that Pasa follows)
- The .fdscript is for internal use, and FD developers may also find it useful to control the "ghost" option by the script file. 
- When we use .fdscript to run an analysis, we first open the model using the .struxml then we specify the calculation settings and run the calculation. In this way we use the settings defined in .fdscript and due to the command order these settings will overwrite the previous attributes in the opened model.

**~> Conclusion:**
We need to be aware that the .fdscript can overwrite the .struxml attributes, so we will have to deal with this in the future if the construction stages are going to play a bigger role.

**time-dependent_analysis** and **creep_strain_increment_limit:**

- They are in the model objects, so they are similar to the **ghost**.
- These are not yet included in .fdscript, because Pasa hasn't implemented them yet, but he will.

**Comment by Marco-Pellegrino** [comment]
Perfect!
Thanks @lorinczandrea
