### ISSUE TITLE
peak smooth region empty

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#814]
_Sorry my previous message wasn’t clear. I meant that SmRegion is empty in Model.Deconstruct when I load a model with peak smoothing regions in Grasshopper._

https://strusoft.freshdesk.com/a/tickets/33970

**Comment by lorinczandrea** [comment]
I checked Alexandre's .struxml files and they don't contain any peak_smoothing_region attribute, so that is the reason, why he cannot see them in GH. The weird part is that I tried to open and save the files again, with smoothing regions I created, but I couldn't export them to the .struxml file. I think it's an FD issue. I have to talk with Laci about this, but he is on holiday.

**Comment by lorinczandrea** [comment]
We found the bug. The difference between the two regions: the first is generated automatically by FD, the second was copied and created manually.

![image](https://github.com/strusoft/femdesign-api/assets/107181445/d7325e06-caa9-4365-a87f-e8955c1504cf)

**Issue:** We cannot export generated peak smoothing regions now. 
**FogBugz case:** https://strusoft.fogbugz.com/f/cases/127622/Struxml-Export-of-automatically-generated-peak-smoothing-regions-not-possible

**Comment by lorinczandrea** [comment]
Until the FogBugz case is solved, if the user wants to use the SmRegion, they need to "convert" the generated ones into exportable objects. A simple way to do this is to copy the generated regions in FEM-Design. Then the "peak_smoothing_region" attributes should appear in struxml.
