### ISSUE TITLE
Peak smooth region do not get serialise if automatically generated

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#817]
#814 follow up of a user request

https://strusoft.fogbugz.com/f/cases/127622/Struxml-Export-of-automatically-generated-peak-smoothing-regions-not-possible

**Comment by lorinczandrea** [comment]
### FD developer's answer: 
Automatically generated peak smoothing regions cannot be exported to .struxml because it makes no sense (they are automatic). Exporting aut. gen. psr. as manually created is dangerous. If the user doesn't turn off the aut. gen. psr. function in FD Settings, then after reopening the file, the user will get both the exported and aut. gen. psr. regions.

### Conclusion:
The user has to know and understand what he is doing and **be careful not to duplicate** the regions, thus **turn off the aut. gen. in FD Settings.**

### Note 1:
Solution to get the aut. gen. psr. in Grasshopper: https://github.com/strusoft/femdesign-api/issues/814#issuecomment-1632269881

### Note 2:
FD will generate the psr at any time if the function is turned on in Settings 
![image](https://github.com/strusoft/femdesign-api/assets/107181445/c9e59514-f861-4641-aecf-f3bf8bbdb901)

...and:

1. the user clicks on the "Peak smoothing region" option on Finite elements tab 
![image](https://github.com/strusoft/femdesign-api/assets/107181445/57ad3fd1-044c-44ce-8364-18b29056ec8a)

2. or runs an analysis.
