### ISSUE TITLE
One deconstructor to rule them all! 💥

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#92]
## What?
Maybe we could implement **1** deconstruct component to be used for all objects in the API (and others as well). 
This means that we don't have to create a decontruct-component for every element and most importantly not for every result class.

## How?
This could be similar to how the `Explode` component in the `BHoM` framework works. But this component would be included in our API. 

## Inspiration
[jSwan](https://www.food4rhino.com/en/app/jswan)
[ExplodeAnything](https://www.food4rhino.com/en/app/explodeanything)
[BHoM](https://github.com/BHoM/Grasshopper_Toolkit/blob/main/Grasshopper_UI/Components/Engine/Explode.cs)

**Comment by Marco-Pellegrino** [comment]
@andosca 

Our API is getting BIGGER day by day and I have started feeling that our Deconstructors are risking to become infinite.

We should consider spending some time doing some research on this topic and we would make several user happy.

A nice solution to keep all the work that it has been done, would be to follow bhom workflow but we should call an already created component instead of going through the property (which it might be possible anyway hiding some of them with some special attribute)

**Comment by andosca** [comment]
I agree that this is becoming more and more acute of a problem. I think we need to have a open discussion about how to move forward to make sure we can construct, deconstruct and modify our elements while keeping the necessary XML-serialisation functionality working and not making every weird private field visible to the user.

**Comment by andosca** [comment]
https://github.com/orgs/strusoft/teams/api/discussions/5

**Comment by andosca** [comment]
Different decision taken.
